I had not uploaded the trained model

python udc_train.py

python udc_predict.py --model=runs/1495043689/
